### ISSUE TITLE
Hotlinking and download_location problems

### ISSUE THREAD

**Issue by anonimeishon** [unsplash/unsplash-js#179]
#### Steps to Reproduce

- In my application I'm trying to let people choose photos from the Unsplash API as their profile pictures and etc, but I'm trying to fix my unsplash integration so I can apply for a production API key, I'm having issues understanding how hotlinking works, do I need to save the download_location and when loaded in my webpage request your api again to get the url.small link with the utm query?
Or do I just save the url.small link with the query directly? 
Thanks in advance!

**Comment by steve-gio** [comment]
Same issue here

**Comment by OliverJAsh** [comment]
Hi, this article should provide all of the information you need: https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download

Essentially, you want to send a request to the URL specified at `photo.links.download_location` when the user chooses a photo to use as their profile picture.

I'm going to close this as it's a API support issue rather than an issue with `unsplash-js`.
