### ISSUE TITLE
unsplash is not working with React native

### ISSUE THREAD

**Issue by javierdac** [unsplash/unsplash-js#182]
#### Steps to Reproduce

Create a simple project in React and add the unsplash library
-

#### Observed Behaviour

-
not implemneted error

> _Image or video please._

![Simulator Screen Shot - iPhone 12 - 2021-07-14 at 13 50 10](https://user-images.githubusercontent.com/1247007/125661276-50bd16a1-b610-4cb2-b347-b0e447947e42.png)

#### Expected Behaviour

-

#### Technical Notes

-

**Comment by OliverJAsh** [comment]
Please provide steps to reproduce with a reduced test case we can clone. In the meantime I will close this as it's not something we can help with.

**Comment by javierdac** [comment]
@OliverJAsh can i use unsplash api with react native? I saw every single issue closed without a solution.

**Comment by OliverJAsh** [comment]
> We […] removed support in the new version because our primary target audience is browser/Node, not React Native.

https://github.com/unsplash/unsplash-js/issues/170#issuecomment-821091372

As per that comment, we would consider contributions to fix this, but it's not a priority for us.

**Comment by deepakkumardk** [comment]
Hi @javierdac & @OliverJAsh I have managed to fix this issue by using this package [react-native-url-polyfill](https://github.com/charpeni/react-native-url-polyfill)

The problem here is that react-native doesn't understand the URL object, if you console log any URL object it will print the URL in string format while the same is not the case with browsers (here it prints out the object and its corresponding properties). The same is explained well in the above library readme file, please have a look there.

Just following the installation steps for the above polyfill library fixes this issue, so without making any changes to unsplash-js library, we can just add it to the documentation, which would be a great help for react-native developers.
