### ISSUE TITLE
Options headers for CORS

### ISSUE THREAD

**Issue by drKnoxy** [unsplash/unsplash-js#26]
OPTIONS: `Access-Control-Allow-Headers` missing `authorization` and `accept-version`.

Are there any projects that actually use this? or is it only meant to be for node apps?

**Comment by matthiasg** [comment]
Removing all headers from the function `buildFetchOptions` function and adding the Client-ID as an url parameter gets rid of this issue btw but this is only a temp patch since the API does want headers such as Accept-Version etc. These and other custom headers will cause CORS to run the OPTIONS request and unsplash does not seem to allow that. I would say its an issue with the OPTIONS response by the unsplash API.

**Comment by duyhung85** [comment]
I am having the same problem of "Fetch API cannot load..." and googling for a while but no luck. I will try matthiasg work around but please fix the Unsplash API.

**Comment by bfintal** [comment]
Been encountering this too.

**Comment by lukechesser** [comment]
@aaronklaassen do you know if this is no longer a problem? Or are we still working around this?

**Comment by aaronklaassen** [comment]
@lukechesser Yes, this should be fixed. Though if anyone finds otherwise let me know: api@unsplash.com

**Comment by pmactavish13** [comment]
I am getting
 The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.
I have the client_id and key in the url.  doesnt work.

**Comment by lukechesser** [comment]
@pmactavish13 I'm going to guess that it was a stray error from our CDN, which has increased over the past week (see status.unsplash.com). When an error happens at the CDN level, the CORS headers aren't set currently.

We're going to update that error response at the CDN level though
