### ISSUE TITLE
CORS issue on 500 responses

### ISSUE THREAD

**Issue by PlanetIrata** [unsplash/unsplash-js#47]
Hi, I'm using unsplash-js for a while and all was working fine, but now I have CORS issues. Here is the console log while running a simple `unsplash.search.photos('food', 1, 30)` :
```
GET https://api.unsplash.com/search/photos?query=food&page=1&per_page=30 503 ()

Failed to load https://api.unsplash.com/search/photos?query=food&page=1&per_page=30: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 503. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.-

```

Is it a problem on Unsplash side ?

Thanks

**Comment by Nodman** [comment]
I'm experiencing same issue. =(

**Comment by FalkoJoseph** [comment]
Yes, same here. Any solutions or workarounds?

**Comment by naoufal** [comment]
@PlanetIrata I'm not sure how this ever worked for you since you're initiating network calls from localhost (which are blocked by CORS). 

You have two options:
- Map localhost to a dev URL. Something like your app.dev.
- Disable CORS/Web Security. 

The second option is probably the easiest. There are since Chrome extensions that do this for you. 

Might also be worth familiarizing yourself with CORS too.

**Comment by PlanetIrata** [comment]
@naoufal My app proxy the requests to avoid CORS issues, it was working correctly for several days before the problem occurs. And it has worked again a few hours after the issue, maybe it was a problem with my proxy or with Unsplash (which has reported a server issue at the same time of the issue). Don't know...but it works fine again.

**Comment by naoufal** [comment]
Well, in the error message you posted the request seems to be coming from http://localhost:3000.

So the error is likely due to the fact that you somehow started initiating requests from localhost.

**Comment by jammer99** [comment]
Hello, Sorry to revive a closed topic, but the issue seems persistent, I am simply visiting the page in my browser, which should not raise any CORS issues, it still shows me 503. Please refer the attached image
![desktop screenshot](https://user-images.githubusercontent.com/9447220/30772148-530ad71e-a073-11e7-95f3-3d25fa18e842.png)

**Comment by lukechesser** [comment]
Hey @jammer99 yeah thats a different problem. We've had a few issues with timeouts over the past few weeks if you check our [status page](status.unsplash.com). It's unrelated to CORS

**Comment by jammer99** [comment]
Thats exactly what i wanted to say, because when the response is proper (200), there is the CORS header present, just when there is a 5xx response, no CORS header is sent. @lukechesser

**Comment by lukechesser** [comment]
Ah gotcha @jammer99 thanks. I'll look into our varnish config, thanks.

**Comment by jrvscm** [comment]
Was there ever a fix for this? Noticing it as of 3/20/2018. it looks like the API was having some issues, status is set to Major Outage.

**Comment by mohammadrahmat** [comment]
Still getting this issue as of 21/3/2018

**Comment by lukechesser** [comment]
Sorry, been meaning to look into this

**Comment by samijaber** [comment]
Closing as this issue is an API support issue and not relevant to this repo.
