### ISSUE TITLE
is there any way to get a list of tags for an unsplash image?

### ISSUE THREAD

**Issue by HassanMehdi17** [unsplash/unsplash-js#59]

**Comment by w0bbes** [comment]
Any comment on this? Would be really cool to have!

**Comment by lukechesser** [comment]
This isn't something we publicly support.

Tags are represented as a series of confidences and scores in our backend system, so we don't publicly support exposing them and there's no real practical use for exposing them. You will find tags in privately documented fields, but use them at your own risk because we may change those fields at any time.

**Comment by joaonew** [comment]
I see a practical use, if I have a screen where I allow users to search for Unsplash images, it would be cool when they type, for example, "Dog", I can give him suggestions on other querries he can make related to that, e.g.: "Cat", "Pets", "FLuffy", tags that are trending in unsplash or just related to that querry somehow.
