### ISSUE TITLE
Module name "unsplash-js" has not been loaded yet

### ISSUE THREAD

**Issue by tobyelliott** [unsplash/unsplash-js#93]
#### Steps to Reproduce

- HTML: `<script async data-main="index.js" src="require.js"></script>`
- JavaScript:
```
// Require syntax
const Unsplash = require("unsplash-js").default;

const unsplash = new Unsplash({
  applicationId: "[removed]",
  secret: "[removed]"
});
```

#### Observed Behaviour

- It errors.

#### Expected Behaviour

- It to work as per the documentation.

#### Technical Notes

- Error: Uncaught Error: Module name "unsplash-js" has not been loaded yet for context: _. Use require([])

**Comment by samijaber** [comment]
You're using the `async` attribute, so the script is not guaranteed to have loaded in time. You'll need to drop `async` or explicitly check that it's been loaded before trying to use anything.

This might be of some help: https://stackoverflow.com/questions/40193553/load-event-on-script-with-async-and-or-defer/40193733

**Comment by tobyelliott** [comment]
@samijaber It errors without using `async`.

**Comment by samijaber** [comment]
Well, either way, the error is not related to our package. It's got to do with how you require modules in your project, which I can't directly help you with since it depends on how you've set things up on your end.

Searching for the error shows me this: https://requirejs.org/docs/errors.html#notloaded
